Nueva clase Portal
brianstanley/tp2-algo-prueba pull request #6
Opened 2018-10-21 20:22 UTC by yorickeando

Y formato de celula cambiado.

2018-10-22 00:56 UTC, germandawi approved these changes
todo correcto, le doy ok

2018-10-22 20:58 UTC, RodriguezNazareno56 approved these changes

2018-10-22 21:42 UTC, brianstanley requested changes
Lo veo bien metí unos comments para cambiar unas boludeces

2018-10-22 21:42 UTC, brianstanley commented on src/CoordenadaParcela.cpp
> +CoordenadaParcela CoordenadaParcela::getCoordenadaParcela() {
Hay que sacarlo. Cuando tenes la instancia de la Coordenada ya tenes todo lo necesario. Ej:
```
CoordenadaParcela parcela;
int coordX =  parcela.getCoordenadaX();
int coordY =  parcela.getCoordenadaY();
```

2018-10-22 21:42 UTC, brianstanley commented on src/Portal.h
> +	CoordenadaParcela parcelaAsociada;
Me parece que debería ser:
`CoordenadaParcela * parcelaAsociada;`

2018-10-22 21:42 UTC, brianstanley commented on src/Portal.cpp
> +		CoordenadaParcela parcelaPareja) {
@yorickeando y si lo tratamos a parcelaPareja como un *puntero* a una parcela?

2018-10-22 23:53 UTC, yorickeando commented on src/Portal.cpp
> +		CoordenadaParcela parcelaPareja) {
Me parece inteligente.

2018-10-22 23:54 UTC, yorickeando commented on src/Portal.h
> +	CoordenadaParcela parcelaAsociada;
Si, mismo comentario que lo del puntero, me imagino.

2018-10-22 23:54 UTC, yorickeando commented on src/CoordenadaParcela.cpp
> +CoordenadaParcela CoordenadaParcela::getCoordenadaParcela() {
Claro.

2018-10-24 23:40 UTC, brianstanley approved these changes
lo veo bien :+1:

2018-10-24 23:40 UTC, merged