Agregar imagen de tablero
brianstanley/tp2-algo-prueba pull request #9
Opened 2018-10-24 21:44 UTC by germandawi

aca subo la clase para crear las imagenes del tablero y un .h y .cpp  que contienen las funcioines que hice para transformar los int a string.

2018-10-25 21:10 UTC, brianstanley requested changes

2018-10-25 21:10 UTC, brianstanley commented on libreria/EasyBMP.h
> +/*************************************************
@germandawi Buenísimo la separación en otra carpeta!
Renombra la carpeta a `librerias`, se suelen usar en plural por convención.

2018-10-25 21:10 UTC, brianstanley commented on src/imagen_de_tablero.cpp
> +const int profundidadDeColorStandar = 8;
las constantes siempre con mayúscula

2018-10-25 21:10 UTC, brianstanley commented on src/imagen_de_tablero.h
> +	BMP archivoRepresentante;
por qué archivoRepresentante? me parece que `archivoBmp` o algo por el estilo tendría mas sentido. qué opinás?

2018-10-25 21:10 UTC, brianstanley commented on src/funciones_transformar_int_string.h
> +/*
Al archivo lo llamaría funciones_string.h porque por ahí vamos a tener q implementar mas cosas para manejos de strings y podemos ir agregando los métodos acá

2018-10-25 21:20 UTC, germandawi commented on src/funciones_transformar_int_string.h
> +/*
El tema es que si lo que vos y yorick me pasaron funciona entonces eliminaria estos .cpp y .h para transformar int a string. Esa seria la idea

2018-10-25 21:28 UTC, yorickeando commented on src/imagen_de_tablero.cpp
> +void ImagenDeTablero::guardarImagenTabero(int numeroDeTurno){
tablero y no tabero

2018-10-25 21:28 UTC, yorickeando commented on src/imagen_de_tablero.h
> +	void guardarImagenTabero(int NumeroDeTurno);
tablero y no tabero

2018-10-25 21:44 UTC, yorickeando commented on src/imagen_de_tablero.h
> +	 * post: se guarda un archivo.bmp con la representacion de las celulas en el tablero
Me parece que faltan unas especificaciones en el pre/pos, no entiendo bien cuando se usa. El numero de turno cuando aparece?

2018-10-25 22:32 UTC, germandawi commented on src/imagen_de_tablero.h
> +	 * post: se guarda un archivo.bmp con la representacion de las celulas en el tablero
se supone que este metodo se usa para representar celulas muertas en el archivo .bmp.
Si la celula en cuestion tiene estado muerto se usa este metodo que pinta el pixel que representa a la celula de blanco.

2018-10-25 22:53 UTC, germandawi commented on src/imagen_de_tablero.h
> +	BMP archivoRepresentante;
ok, le pongo archivoBmp

2018-10-25 23:55 UTC, germandawi commented
hice un nuevo merge donde resolvi los problemas marcados y deje la parte de la converison de int a string con dos opciones

2018-10-26 14:34 UTC, yorickeando commented on src/imagen_de_tablero.h
> +	 * post: se guarda un archivo.bmp con la representacion de las celulas en el tablero
Gracias, pero estoy hablando del de abajo jaja

2018-10-26 18:29 UTC, brianstanley approved these changes
muy bien! :clap: 
@germandawi te compiló todo bien no?
te lo apruebo no sé si falta algo más @yorickeando

2018-10-27 16:51 UTC, merged